### ISSUE TITLE
Results in Internet Explorer 11

### ISSUE THREAD

**Issue by RogerLawson** [chrisjfield/CompositionProver#1]
When using Internet Explorer 11, I can enter a composition but when I click on the "RESULTS" tab all the tabs disappear and I don't get anything.  

![comp-prover-results_in_ie11](https://user-images.githubusercontent.com/35303024/34780879-3c5a5694-f61c-11e7-897e-b909dc9d9e41.JPG)

The other tabs all seem to work OK and "RESULTS" works OK in Chrome.  

Any suggestions (apart from "don't use IE")?

**Comment by chrisjfield** [comment]
Hi Roger, 

Sorry for not seeing this for ages! I'll have a look and get back to you.

**Comment by chrisjfield** [comment]
@RogerLawson should be fixed now
